### ISSUE TITLE
how to run backend 

### ISSUE THREAD

**Issue by ankitdata** [mlmed/chester-xray#11]
Hi,

I want to run the python backend and print results in console by using [models](https://github.com/mlmed/chester-xray/tree/master/models) .
(only jupyter notebooks in [scripts](https://github.com/mlmed/chester-xray/tree/master/scripts))

what will be the jupyter notebooks sequence ?
which ipynb file will help me to print results ?

_Thanks_.

**Comment by ieee8023** [comment]
There is no backend. Everything runs in the browser. Look at system.js. Here is the paper about the project: https://arxiv.org/abs/1901.11210
